
1. Create a pandas DataFrame from the lists above. Write a code to check if there are any missing values in the DataFrame.

In [1]:

import pandas as pd
import numpy as np


names = ["Kelly", np.nan, 'Jon', 'Ken', 'Tim', 'Pel']
grades = [30, 40, 30, 67, np.nan, 55]
age =[15, np.nan, 18, 17, np.nan, 16]

df = pd.DataFrame({'Names': names,'Grades':grades,'Age': age})
df

   Names  Grades   Age
0  Kelly    30.0  15.0
1    NaN    40.0   NaN
2    Jon    30.0  18.0
3    Ken    67.0  17.0
4    Tim     NaN   NaN
5    Pel    55.0  16.0

In [2]:

# Checking for missing values
df.isnull().sum()

Names     1
Grades    1
Age       2
dtype: int64


2. Your supervisor has asked that you show them how to fill the missing values, using the library scikit-learn. Write a code to fill missing values in the DataFrame above using this library. Use the most_frequent strategy for the "Names" column. Mean strategy for the "Grades" column. Median strategy for the "Age" column. Make a copy of the original DataFrame

In [3]:
from sklearn.impute import SimpleImputer

df2 = df.copy()

# creating an instance of SimpleImputer with different strategies for each column
imputer_names = SimpleImputer( strategy='constant',fill_value="Paul",)
imputer_grades = SimpleImputer(strategy='mean')
imputer_age = SimpleImputer(strategy='median')

df2[['Names']] = imputer_names.fit_transform(df2[['Names']])
df2[['Grades']] = imputer_grades.fit_transform(df2[['Grades']])
df2[['Age']] = imputer_age.fit_transform(df2[['Age']])

df2

   Names  Grades   Age
0  Kelly    30.0  15.0
1   Paul    40.0  16.5
2    Jon    30.0  18.0
3    Ken    67.0  17.0
4    Tim    44.4  16.5
5    Pel    55.0  16.0


3. Using the original DataFrame (question 1) with missing values, identify and drop any columns that have more than 30% missing values. Save this to a new variable.

In [4]:
# Check percentage of missing values in each column
missing_values = df.isnull().mean()

# Select columns that have more than 50% missing values
columns_to_drop = missing_values[missing_values > 0.30].index

# Drop columns from the dataframe
df_cleaned = df.drop(columns_to_drop, axis=1)

df_cleaned

   Names  Grades
0  Kelly    30.0
1    NaN    40.0
2    Jon    30.0
3    Ken    67.0
4    Tim     NaN
5    Pel    55.0


4. Using pandas, check for any duplicate values in the "Names" columns of your DataFrame ( question 3).

In [5]:
df_cleaned.duplicated("Names").sum()

np.int64(0)


5. Use the pandas groupby() method and agg() method to calculate the mean, minimum, and maximum of the "Grades" column, grouped by the "Names" column. Use the a copy of the DataFrame you saved in question 2.

In [6]:
sch_data_agg = df2.groupby('Names').agg({'Grades': ['mean', 'min', 'max']})
sch_data_agg

      Grades
        mean   min   max
Names
Jon     30.0  30.0  30.0
Kelly   30.0  30.0  30.0
Ken     67.0  67.0  67.0
Paul    40.0  40.0  40.0
Pel     55.0  55.0  55.0
Tim     44.4  44.4  44.4